version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:$PORT
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:${PORT}"
    env_file: .env
    depends_on:
      - db
